version: '3'

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:latest
    container_name: wireguard
    env_file: .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - ${SERVERPORT}:${SERVERPORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      - wg
  peers-generator:
    image: ghcr.io/d1ffic00lt/peers-generator:latest
    env_file: .env
    environment:
      TOKEN: /run/secrets/telegram-token
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - telegram-token

networks:
  wg:
    driver: bridge

secrets:
  telegram-token:
    file: ./secrets/telegram-token.txt

