version: '3'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    env_file: .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
  peers-generator:
    build: peers-generator
    env_file: .env
    volumes:
      - ./config:/config
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: bridge
